//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxem.Checks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taxem.Checks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio,trade id,product, ,created at,size,size unit,price,fee,total,price/fee/total unit
        ///default,12345,BAT-ETH,BUY,2019-10-16T20:03:05.219Z,123.00000000,BAT,0.00127110,0.001754118,-0.352577718,ETH
        ///default,22222,BAT-ETH,BUY,2019-10-16T23:31:03.304Z,2.00000000,BAT,0.00123500,0.00025935,-0.05212935,ETH
        ///default,30000,BAT-ETH,BUY,2019-10-17T04:01:24.219Z,300.00000000,BAT,0.00123500,0.00159315,-0.32022315,ETH
        ///
        ///.
        /// </summary>
        internal static string HeaderContainsConsecutiveCommas {
            get {
                return ResourceManager.GetString("HeaderContainsConsecutiveCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio trade id
        ///default, foo
        ///default, 22222, BAT-ETH
        ///ksjdj 980348tu ekjdth, 208y 043ih, fwje wphy 80whyeg.df,s,&apos;xxpv s[dj dg[]pr]gu ihg
        ///.
        /// </summary>
        internal static string HeaderContainsNoCommas {
            get {
                return ResourceManager.GetString("HeaderContainsNoCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portfolio,trade id,product,side,created at,size,size unit,price,fee,total,price/fee/total unit
        ///default,12345,BAT-ETH,BUY,2019-10-16T20:03:05.219Z,123.00000000,BAT,0.00127110,0.001754118,-0.352577718,ETH
        ///default,22222,BAT-ETH,BUY,2019-10-16T23:31:03.304Z,2.00000000,BAT,0.00123500,0.00025935,-0.05212935,ETH
        ///default,30000,BAT-ETH,BUY,2019-10-17T04:01:24.219Z,300.00000000,BAT,0.00123500,0.00159315,-0.32022315,ETH
        ///.
        /// </summary>
        internal static string ValidTransactions {
            get {
                return ResourceManager.GetString("ValidTransactions", resourceCulture);
            }
        }
    }
}
